LOGIN_DIALOG_TITLE: str = "Вход"
LOGIN_BUTTON_TEXT: str = "Войти"
REGISTER_BUTTON_TEXT: str = "Зарегистрироваться"
LOGIN_LABEL_TEXT: str = "Логин"
PASSWORD_LABEL_TEXT: str = "Пароль"

LOGIN_WINDOW_WIDTH: int = 300
LOGIN_WINDOW_HEIGHT: int = LOGIN_WINDOW_WIDTH // 2
LOGIN_WIDGET_X_OFFSET: int = 10
LOGIN_WIDGET_Y_OFFSET: int = 10
LOGIN_EDITS_HEIGHT: int = 20
