LOGIN_DIALOG_TITLE: str = "Вход"
LOGIN_BUTTON_TEXT: str = "Войти"
REGISTER_BUTTON_TEXT: str = "Зарегистрироваться"
LOGIN_LABEL_TEXT: str = "Логин"
PASSWORD_LABEL_TEXT: str = "Пароль"

NO_LOGIN_OR_PASSWORD: str = "Необходимо ввести логин и пароль"
INCORRECT_CREDS: str = "Логин или пароль введен неверно"
SERVER_ERROR: str = "Сервер недоступен"
ALREADY_REGISTERED: str = "Такой аккаунт уже зарегистрирован"
FILE_NAME: str = "Имя файла"
FILE_GUID: str = "GUID файла"
MAIN_WINDOW_TITLE: str = "LOLDER"
UPLOAD_FILE: str = "Загрузить файл"
ALL_FILES: str = "Все файлы"
DOWNLOAD_ERROR: str = "Ошибка при скачивании файла"
DOWNLOAD_SUCCESS: str = "{} сохранен в {}"
SELECT_FILE: str = "Кликните на файл в таблице"
LINK_SAVED: str = "Ссылка скопирована в буфер обмена"
UPLOAD_ERROR: str = "Ошибка при отправлении файла"
UPLOAD_SUCCESS: str = "Файл {} успешно загружен на сервер"
DELETE_ERROR: str = "Ошибка при удалении файла с сервера"
DELETE_SUCCESS: str = "Файл {} успешно удален с сервера"

LOGIN_WINDOW_WIDTH: int = 300
LOGIN_WINDOW_HEIGHT: int = LOGIN_WINDOW_WIDTH // 2
LOGIN_WIDGET_X_OFFSET: int = 10
LOGIN_WIDGET_Y_OFFSET: int = 10
LOGIN_EDITS_HEIGHT: int = 20
